export const storeConfig = {
  name: 'RebbyStore',
  tagline: 'Your Crown. Your Style.',
  location: 'Ubungo Riverside, Dar es Salaam, Tanzania',
  phone: '0620196710',
  email: 'debbytz@gmail.com',
  currency: 'TSh',
  deliveryFee: 5000,
  freeDeliveryThreshold: 200000,
  social: {
    instagram: 'https://instagram.com/rebbystore',
    whatsapp: 'https://wa.me/255620196710',
    tiktok: 'https://tiktok.com/@rebbystore',
  },
  categories: [
    { id: 'human-hair', label: 'Human Hair', description: 'Premium quality human hair wigs' },
    { id: 'synthetic', label: 'Synthetic', description: 'Affordable synthetic hair wigs' },
    { id: 'lace-front', label: 'Lace Front', description: 'Natural-looking lace front wigs' },
    { id: 'closure', label: 'Closure', description: 'Closure wigs for versatile styling' },
    { id: 'bob', label: 'Bob', description: 'Classic and modern bob styles' },
  ],
  textures: [
    { id: 'straight', label: 'Straight' },
    { id: 'wavy', label: 'Wavy' },
    { id: 'curly', label: 'Curly' },
    { id: 'kinky', label: 'Kinky' },
    { id: 'body-wave', label: 'Body Wave' },
    { id: 'deep-wave', label: 'Deep Wave' },
    { id: 'water-wave', label: 'Water Wave' },
    { id: 'loose-wave', label: 'Loose Wave' },
    { id: 'yaki', label: 'Yaki' },
  ],
  lengths: ['10"', '12"', '14"', '16"', '18"', '20"', '22"', '24"', '26"', '28"', '30"'],
  hairTypes: [
    { id: 'human', label: 'Human Hair' },
    { id: 'synthetic', label: 'Synthetic' },
    { id: 'blend', label: 'Blend' },
  ],
  orderStatuses: [
    { id: 'pending', label: 'Pending', color: 'purple' },
    { id: 'confirmed', label: 'Confirmed', color: 'blue' },
    { id: 'processing', label: 'Processing', color: 'amber' },
    { id: 'ready-for-delivery', label: 'Ready for Delivery', color: 'cyan' },
    { id: 'delivered', label: 'Delivered', color: 'green' },
    { id: 'cancelled', label: 'Cancelled', color: 'red' },
  ],
};
